# Generated by Django 5.1.1 on 2024-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apaterno', models.CharField(max_length=50, verbose_name='APELLIDO PATERNO')),
                ('Amaterno', models.CharField(max_length=50, verbose_name='APELLIDO MATERNO')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE (s)')),
                ('fecha_nacimiento', models.CharField(max_length=100, verbose_name='FECHA DE NACIMIENTO')),
                ('fecha_ingreso', models.CharField(max_length=100, verbose_name='FECHA DE INGRESO')),
            ],
        ),
    ]
